### ISSUE TITLE
Add a new type to define custom regexp

### ISSUE THREAD

**Issue by gustavonecore** [gustavonecore/sanitizer#4]
### Before you start
- [ ] Create a new branch from master using the convention of` feature/{ticket-id}-description`. For this case will be: `feature/5-regexp-type`
- [ ] Every commit should follow the convention: `#{ticket-id} :: {brief-description-of-the-change}`. 

**Example of valid commits**
```ssh
#5 :: Added new regexp type class
#5 :: Refactor of main class in order to simplify strategy
```

**Example of wrong commits**
```ssh
Update of class
Update
5 > Change of logic
```

### Tasks

- [ ] Add a new type class to validate if a string match a given regexp
- [ ] The string used to identify this type would be: `regexp[{expression}]` where `{expression}` will be the regular expression string.
- [ ] Add the related test
- [ ] Update the example code
- [ ] Update the readme

**i.e: We want to create a validation code as follow:**  `^[0-9]{1,6}$`

```ssh
^     : Start anchor
[0-9] : Character class to match one of the 10 digits
{1,6} : Range quantifier. Minimum 1 repetition and maximum 6.
$     : End anchor
```

**Related filter**
```php
$filter = new Gcore\Sanitizer\Template\TemplateSanitizer([
	'email' => 'string',
	'validation_code' => 'regexp[^[0-9]{1,6}$]',
]);
```
